### ISSUE TITLE
[Bug] Cropped image

### ISSUE THREAD

**Issue by Identity-labs** [kngrektor/ytdtool#5]
Images are resized and cropped at import
Tested with 1024x1024

**Comment by kngrektor** [comment]
Hmmm. Image loading itself is handled by the ImageSharp library and I can't find anything obviously wrong with my MipMap generation code, this might be a bug in RageLib. I don't know that I'll have time to fix the issue but either way a repro (I guess just zip up your folder) would help a lot.

**Comment by Identity-labs** [comment]
Yes using wrong MipMap result to cropped img, no issue sorry for inconvenience
